# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: arXiv-daily-ai-enhanced

on:
  schedule:
    # UTC 8:30 = 北京时间 16:30
    - cron: '30 8 * * *'
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv sync
    # - name: Run script
    #   run: |
    #     source .venv/bin/activate
    #     export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
    #     export OPENAI_BASE_URL=${{ secrets.OPENAI_BASE_URL }}
    #     export LANGUAGE="${{ vars.LANGUAGE }}"
    #     export CATEGORIES="${{ vars.CATEGORIES }}"
    #     export MODEL_NAME="${{ vars.MODEL_NAME }}"
    #     bash run.sh
    # - name: commit
    #   run: |
    #     git config --global user.email "${{ vars.EMAIL }}"
    #     git config --global user.name "${{ vars.NAME }}"
    #     git add .
    #     git commit -m "update"
    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set current date
      run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
    - name: Send ServerChan notification
      uses: yakumioto/serverchan-action@v2
      if: always()  # 无论任务成功或失败都发送通知
      with:
        key: ${{ secrets.SERVERCHAN_KEY }}  # 替换为你的 ServerChan SCKEY
        text: "arXiv Daily AI Done" #不能超过 32 字符
        desp: |
          ${{ job.status }}
